version: "3.19"
services:
  database:
    image: postgres:16-alpine
    container_name: database
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 32769:5432
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: ${PGADMIN_CFG_ECP}
    ports:
      - 5050:80
      - 5051:443
    restart: always
    user: pgadmin
    depends_on:
      - database
volumes:
  data:
  pgadmin: